FROM python:3.7.3-alpine3.9

RUN apk update
RUN apk add make automake gcc g++ subversion python3-dev
RUN mkdir -p /app
WORKDIR /app

COPY ./src/requirements.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install dask
RUN pip install numpy
RUN pip install dask[dataframe] --upgrade

COPY ./src/ /app/
ENV FLASK_APP=algorithmservicestart.py

CMD flask run -h 0.0.0.0 -p 7777